services:
  - type: web
    name: Renda-Extra
    env: node
    repo: https://github.com/Hyagoogeda11/Renda-Extra
    branch: main
    buildCommand: npm install && npm install vite && npm run build && npm run preview
    staticPublishPath: ./dist